"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { FALLBACK_DATA } from "../config";
import { formatVietnamDateTime, formatVietnamTime, formatVnd } from "../format";
import type { AppData, Appointment, Order, Partner, PartnerRole, Product } from "../types";

type Panel = "overview" | "appointments" | "records" | "products" | "orders" | "settings";
const money = formatVnd;
const dt = formatVietnamDateTime;

export default function PartnerApp({ initialActor }: { initialActor: AppData["actor"] }) {
  const [data, setData] = useState<AppData>({ ...FALLBACK_DATA, actor: initialActor, requiresSignIn: !initialActor });
  const [loading, setLoading] = useState(true);
  const [panel, setPanel] = useState<Panel>("overview");
  const [partnerId, setPartnerId] = useState("vet-happy-paws");
  const [medicalAppointment, setMedicalAppointment] = useState<Appointment | null>(null);
  const [newProduct, setNewProduct] = useState(false);
  const [toast, setToast] = useState("");
  const [busy, setBusy] = useState("");

  const reload = async () => {
    try {
      const response = await fetch("/api/app", { cache: "no-store" });
      if (!response.ok) throw new Error("Không thể tải dữ liệu");
      const payload = await response.json() as Partial<AppData>;
      setData({ ...FALLBACK_DATA, ...payload, products: payload.products ?? [], partners: payload.partners ?? [], pets: payload.pets ?? [], appointments: payload.appointments ?? [], vaccinations: payload.vaccinations ?? [], medicalRecords: payload.medicalRecords ?? [], partnerRoles: payload.partnerRoles ?? [], partnerAppointments: payload.partnerAppointments ?? [], partnerProducts: payload.partnerProducts ?? [], partnerPets: payload.partnerPets ?? [], orders: payload.orders ?? [], partnerOrders: payload.partnerOrders ?? [] });
    } catch { setData((current) => ({ ...FALLBACK_DATA, actor: current.actor, requiresSignIn: !current.actor })); }
    finally { setLoading(false); }
  };
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void reload(); }, []);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 3000); return () => window.clearTimeout(timer); }, [toast]);

  const activePartnerId = data.partnerRoles.some((role) => role.partner_id === partnerId) ? partnerId : (data.partnerRoles[0]?.partner_id ?? "");
  const currentPartner = data.partners.find((item) => item.id === activePartnerId);
  const activeRole = data.partnerRoles.find((item) => item.partner_id === activePartnerId)?.role;
  const appointments = data.partnerAppointments.filter((item) => item.partner_id === activePartnerId);
  const products = data.partnerProducts.filter((item) => item.partner_id === activePartnerId);
  const orders = data.partnerOrders.filter((item) => item.partner_id === activePartnerId);
  const pending = appointments.filter((item) => item.status === "pending");
  const confirmed = appointments.filter((item) => item.status === "confirmed");
  const canManage = activeRole === "owner" || activeRole === "manager";
  const canSchedule = canManage || activeRole === "staff";
  const canMedical = activeRole === "owner" || activeRole === "clinician";
  const activePanel: Panel = ((panel === "products" || panel === "orders" || panel === "settings") && !canManage) || (panel === "records" && !canMedical) ? "overview" : panel;

  const post = async (body: Record<string, unknown>, success: string) => {
    setBusy(String(body.action ?? "save"));
    try {
      const response = await fetch("/api/app", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      const result = await response.json() as { error?: string };
      if (!response.ok) throw new Error(result.error ?? "Không thể lưu thay đổi");
      setToast(success); await reload(); return true;
    } catch (error) { setToast(error instanceof Error ? error.message : "Không thể lưu thay đổi"); return false; }
    finally { setBusy(""); }
  };

  const updateStatus = async (openNow: boolean, acceptingAppointments: boolean) => {
    await post({ action: "updatePartnerStatus", partnerId: activePartnerId, openNow, acceptingAppointments }, "Trạng thái đã đồng bộ sang app khách hàng.");
  };

  if (loading) return <PartnerAccessGate icon="⌛" title="Đang xác minh phiên đăng nhập" text="PetCare đang kiểm tra quyền truy cập portal đối tác." />;
  if (!data.actor) return <PartnerAccessGate icon="🔒" title="Đăng nhập hoặc đăng ký đối tác" text="Chủ phòng khám và pet shop cần xác thực tài khoản trước khi tạo hồ sơ cơ sở." signIn />;
  if (!data.partnerRoles.length || !currentPartner) return <PartnerRegistrationPage email={data.actor.email} onRegistered={reload} />;

  const actorInitials = data.actor.fullName.split(/\s+/).filter(Boolean).slice(-2).map((part) => part[0]?.toUpperCase()).join("") || "ĐT";

  return <div className="partner-shell">
    <aside className="partner-sidebar">
      <Link className="partner-brand" href="/"><span>P</span><b>PetCare</b><i>Partner</i></Link>
      <nav>{[
        ["overview", "⌂", "Tổng quan", true], ["appointments", "▣", "Lịch hẹn", true], ["records", "♡", "Hồ sơ pet", canMedical], ["products", "◇", "Sản phẩm", canManage], ["orders", "◫", "Đơn hàng", canManage], ["settings", "⚙", "Cài đặt", canManage]
      ].filter((item) => item[3]).map(([id, icon, label]) => <button key={String(id)} className={activePanel === id ? "active" : ""} onClick={() => setPanel(id as Panel)}><span>{icon}</span>{label}{id === "appointments" && pending.length > 0 ? <b>{pending.length}</b> : null}</button>)}</nav>
      <div className="partner-help"><span>?</span><b>Cần hỗ trợ?</b><p>Đội ngũ PetCare phản hồi trong 5 phút.</p><button>Chat với PetCare</button></div>
      <Link className="back-to-shop" href="/">← Về app khách hàng</Link>
    </aside>

    <main className="partner-main-area">
      <header className="partner-topbar"><div><button className="mobile-menu">☰</button><select value={activePartnerId} onChange={(event) => setPartnerId(event.target.value)}>{data.partnerRoles.map((role) => <option key={role.partner_id} value={role.partner_id}>{role.name}</option>)}</select><span className={currentPartner.verified ? "verified-partner" : "pending-partner"}>{currentPartner.verified ? "✓ Đã xác minh" : "⌛ Chờ xác minh"}</span></div><div><button className="notification-button">♢<i>{pending.length}</i></button><div className="partner-user"><span>{actorInitials}</span><p><b>{data.actor.fullName}</b><small>{roleLabel(activeRole)}</small></p></div><a className="partner-top-signout" href="/signout-with-chatgpt?return_to=%2F">Đăng xuất</a></div></header>
      <div className="partner-content">
        {activePanel === "overview" && <Overview partner={currentPartner} pending={pending} confirmed={confirmed} products={products} canManage={canManage} canSchedule={canSchedule} canMedical={canMedical} onStatus={updateStatus} onPanel={setPanel} onAppointment={(appointment) => setMedicalAppointment(appointment)} onDecision={(appointment, status) => void post({ action: "updateAppointmentStatus", appointmentId: appointment.id, status }, status === "confirmed" ? "Đã xác nhận lịch và thông báo cho khách." : "Đã từ chối lịch hẹn.")} busy={busy} />}
        {activePanel === "appointments" && <AppointmentPanel appointments={appointments} canSchedule={canSchedule} canMedical={canMedical} onDecision={(appointment, status) => void post({ action: "updateAppointmentStatus", appointmentId: appointment.id, status }, status === "confirmed" ? "Đã xác nhận lịch hẹn." : "Đã cập nhật lịch hẹn.")} onComplete={setMedicalAppointment} />}
        {activePanel === "records" && canMedical && <RecordsPanel data={data} appointments={appointments} onComplete={setMedicalAppointment} />}
        {activePanel === "products" && canManage && <ProductsPanel products={products} onAdd={() => setNewProduct(true)} onSave={(product, stock, active) => void post({ action: "updateProduct", productId: product.id, stock, active }, "Đã cập nhật tồn kho trên cửa hàng.")} />}
        {activePanel === "orders" && canManage && <OrdersPanel orders={orders} onStatus={(order, status) => void post({ action: "updateOrderStatus", orderId: order.id, status }, "Trạng thái đơn hàng đã đồng bộ với khách.")} />}
        {activePanel === "settings" && canManage && <SettingsPanel partner={currentPartner} onStatus={updateStatus} onProfile={(payload) => void post({ action: "updatePartnerProfile", partnerId: activePartnerId, ...payload }, "Hồ sơ cơ sở đã được cập nhật.")} />}
      </div>
    </main>
    {medicalAppointment && <MedicalModal appointment={medicalAppointment} busy={busy === "addMedicalRecord"} onClose={() => setMedicalAppointment(null)} onSubmit={async (payload) => { if (await post({ action: "addMedicalRecord", appointmentId: medicalAppointment.id, ...payload }, "Hồ sơ y tế đã cập nhật và đồng bộ cho chủ pet.")) setMedicalAppointment(null); }} />}
    {newProduct && <ProductModal partnerId={activePartnerId} busy={busy === "createProduct"} onClose={() => setNewProduct(false)} onSubmit={async (payload) => { if (await post({ action: "createProduct", partnerId: activePartnerId, ...payload }, "Sản phẩm đã được đăng lên cửa hàng.")) setNewProduct(false); }} />}
    {toast && <div className="partner-toast" role="status">{toast}</div>}
  </div>;
}

function PartnerAccessGate({ icon, title, text, signIn = false, signedInEmail }: { icon: string; title: string; text: string; signIn?: boolean; signedInEmail?: string }) {
  return <main className="partner-access-page"><section><Link className="partner-brand" href="/"><span>P</span><b>PetCare</b><i>Partner</i></Link><div className="partner-access-icon">{icon}</div><h1>{title}</h1><p>{text}</p>{signedInEmail && <small>Đang đăng nhập: {signedInEmail}</small>}{signIn ? <a className="portal-primary" href="/signin-with-chatgpt?return_to=%2Fpartner">Tiếp tục đăng nhập / đăng ký</a> : signedInEmail ? <a className="partner-signout" href="/signout-with-chatgpt?return_to=%2F">Đăng xuất</a> : null}</section></main>;
}

function roleLabel(role?: PartnerRole) {
  return role === "owner" ? "Chủ cơ sở" : role === "manager" ? "Quản lý" : role === "clinician" ? "Bác sĩ thú y" : role === "staff" ? "Nhân viên" : "Đối tác";
}

function PartnerRegistrationPage({ email, onRegistered }: { email: string; onRegistered: () => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [coords, setCoords] = useState({ latitude: "", longitude: "" });
  const locate = () => { if (!navigator.geolocation) { setError("Thiết bị không hỗ trợ định vị."); return; } navigator.geolocation.getCurrentPosition((position) => setCoords({ latitude: String(position.coords.latitude), longitude: String(position.coords.longitude) }), () => setError("Không lấy được vị trí. Bạn có thể nhập tọa độ thủ công."), { enableHighAccuracy: true, timeout: 8000 }); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(""); const f = new FormData(event.currentTarget); try { const response = await fetch("/api/app", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "registerPartner", name: f.get("name"), partnerType: f.get("partnerType"), address: f.get("address"), phone: f.get("phone"), hours: f.get("hours"), services: f.get("services"), latitude: Number(coords.latitude), longitude: Number(coords.longitude) }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Không thể đăng ký cơ sở"); await onRegistered(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Không thể đăng ký cơ sở"); } finally { setBusy(false); } };
  return <main className="partner-registration-page"><section><header><Link className="partner-brand" href="/"><span>P</span><b>PetCare</b><i>Partner</i></Link><a href="/signout-with-chatgpt?return_to=%2F">Đăng xuất</a></header><div className="registration-heading"><span>✓ Tài khoản đã xác thực</span><h1>Đăng ký hồ sơ cơ sở</h1><p>Bạn sẽ được cấp role <b>Chủ cơ sở (owner)</b>. Cơ sở chỉ xuất hiện công khai sau khi PetCare xác minh.</p><small>{email}</small></div><form className="partner-registration-form" onSubmit={submit}><label>Tên phòng khám / pet shop<input name="name" required maxLength={160} /></label><label>Loại cơ sở<select name="partnerType" required><option value="vet">Phòng khám thú y</option><option value="shop">Pet shop</option><option value="both">Thú y & pet shop</option></select></label><label className="wide">Địa chỉ<input name="address" required maxLength={300} /></label><label>Số điện thoại<input name="phone" required maxLength={30} placeholder="028 1234 5678" /></label><label>Giờ hoạt động<input name="hours" required maxLength={160} placeholder="07:30–21:00 mỗi ngày" /></label><label className="wide">Dịch vụ<textarea name="services" required maxLength={500} placeholder="Khám tổng quát, Tiêm phòng, Grooming" /></label><div className="coordinate-fields"><label>Vĩ độ<input value={coords.latitude} onChange={(event) => setCoords((current) => ({ ...current, latitude: event.target.value }))} type="number" step="any" min="-90" max="90" required /></label><label>Kinh độ<input value={coords.longitude} onChange={(event) => setCoords((current) => ({ ...current, longitude: event.target.value }))} type="number" step="any" min="-180" max="180" required /></label><button type="button" onClick={locate}>⌖ Dùng vị trí hiện tại</button></div>{error && <p className="form-error">{error}</p>}<button className="portal-primary registration-submit" disabled={busy}>{busy ? "Đang tạo hồ sơ..." : "Đăng ký với role chủ cơ sở"}</button><small className="registration-security">🔒 Không lưu mật khẩu; quyền owner được kiểm tra ở backend cho mọi thao tác.</small></form></section></main>;
}

function PageTitle({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: React.ReactNode }) { return <div className="partner-page-title"><div><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{action}</div>; }

function Overview({ partner, pending, confirmed, products, canManage, canSchedule, canMedical, onStatus, onPanel, onAppointment, onDecision, busy }: { partner: Partner; pending: Appointment[]; confirmed: Appointment[]; products: Product[]; canManage: boolean; canSchedule: boolean; canMedical: boolean; onStatus: (open: boolean, accepting: boolean) => void; onPanel: (panel: Panel) => void; onAppointment: (appointment: Appointment) => void; onDecision: (appointment: Appointment, status: "confirmed" | "cancelled") => void; busy: string }) {
  const todayCount = pending.length + confirmed.length;
  const todayLabel = "Hôm nay";
  return <>
    <PageTitle eyebrow={`Xin chào đội ngũ ${partner.name} 👋`} title="Hôm nay có gì?" text="Mọi hoạt động quan trọng của cơ sở trong một màn hình." action={<div className="live-status"><i className={partner.open_now ? "online" : ""}/><span><b>{partner.open_now ? "Đang hiển thị mở cửa" : "Đang hiển thị đóng cửa"}</b><small>{partner.verified ? "Khách hàng thấy trạng thái này ngay lập tức" : "Sẽ công khai sau khi cơ sở được xác minh"}</small></span><label className="switch"><input type="checkbox" checked={Boolean(partner.open_now)} disabled={!canManage} onChange={(event) => void onStatus(event.target.checked, Boolean(partner.accepting_appointments))}/><span/></label></div>} />
    <div className="partner-kpis"><article><span className="kpi-icon coral">▣</span><div><small>Lịch hẹn hôm nay</small><b>{todayCount}</b><em>+2 so với hôm qua</em></div></article><article><span className="kpi-icon mint">⌛</span><div><small>Chờ xác nhận</small><b>{pending.length}</b><em>Cần xử lý sớm</em></div></article><article><span className="kpi-icon blue">🐾</span><div><small>Hồ sơ đã chăm sóc</small><b>1,284</b><em>+8 tuần này</em></div></article><article><span className="kpi-icon gold">◇</span><div><small>Sản phẩm đang bán</small><b>{products.length}</b><em>{products.filter((p) => p.stock < 20).length} sắp hết hàng</em></div></article></div>
    <div className="partner-overview-grid">
      <section className="partner-panel"><div className="partner-panel-head"><div><h2>Lịch hẹn cần xử lý</h2><p>Duyệt sớm để khách an tâm chuẩn bị cho bé</p></div><button onClick={() => onPanel("appointments")}>Xem tất cả →</button></div><div className="request-list">{pending.map((appointment) => <AppointmentRow key={appointment.id} appointment={appointment} actions={canSchedule ? <><button className="decline" disabled={Boolean(busy)} onClick={() => onDecision(appointment, "cancelled")}>Từ chối</button><button className="accept" disabled={Boolean(busy)} onClick={() => onDecision(appointment, "confirmed")}>✓ Xác nhận</button></> : <span className="portal-status">Chỉ xem</span>} />)}{!pending.length && <div className="partner-empty"><span>✓</span><b>Đã xử lý hết yêu cầu</b><p>Không còn lịch nào đang chờ.</p></div>}</div></section>
      <aside className="today-panel"><div className="partner-panel-head"><div><h2>Ca khám tiếp theo</h2><p>{todayLabel}</p></div></div>{confirmed[0] ? <div className="next-visit"><div className="time-line"><b>{formatVietnamTime(confirmed[0].scheduled_at)}</b><span/><small>30 phút</small></div><div className="visit-pet"><span>{confirmed[0].pet_avatar ?? "🐶"}</span><div><b>{confirmed[0].pet_name}</b><small>{confirmed[0].pet_breed}</small></div></div><h3>{confirmed[0].reason}</h3><p>“{confirmed[0].note}”</p>{canMedical && <button onClick={() => onAppointment(confirmed[0])}>Mở ca khám →</button>}</div> : <div className="partner-empty"><span>☕</span><b>Chưa có ca tiếp theo</b></div>}<div className="schedule-mini">{confirmed.slice(1,4).map((item) => <span key={item.id}><b>{formatVietnamTime(item.scheduled_at)}</b><i>{item.pet_name}</i><em>{item.reason}</em></span>)}</div></aside>
    </div>
    <section className="insight-banner"><span>✦</span><div><b>{partner.verified ? "Mẹo từ PetCare" : "Hồ sơ đang chờ xác minh"}</b><p>{partner.verified ? "Bật “Đang nhận lịch” giúp cơ sở xuất hiện cao hơn khi khách tìm thú y gần nhất." : "Bạn vẫn có thể hoàn thiện sản phẩm và hồ sơ; khách chỉ thấy cơ sở sau khi được duyệt."}</p></div><label className="switch"><input type="checkbox" checked={Boolean(partner.accepting_appointments)} disabled={!canManage} onChange={(event) => void onStatus(Boolean(partner.open_now), event.target.checked)}/><span/></label><strong>{partner.accepting_appointments ? "Đang nhận lịch" : "Tạm ngưng nhận lịch"}</strong></section>
  </>;
}

function AppointmentRow({ appointment, actions }: { appointment: Appointment; actions?: React.ReactNode }) { return <article className="partner-appointment-row"><span className="pet-mini">{appointment.pet_avatar ?? "🐾"}</span><div className="request-pet"><b>{appointment.pet_name}</b><small>{appointment.pet_breed} · {appointment.owner_email}</small></div><div><small>Thời gian</small><b>{dt(appointment.scheduled_at)}</b></div><div><small>Lý do</small><b>{appointment.reason}</b></div><div className="row-actions">{actions}</div></article>; }

function AppointmentPanel({ appointments, canSchedule, canMedical, onDecision, onComplete }: { appointments: Appointment[]; canSchedule: boolean; canMedical: boolean; onDecision: (appointment: Appointment, status: "confirmed" | "cancelled") => void; onComplete: (appointment: Appointment) => void }) {
  const [filter, setFilter] = useState("all"); const filtered = filter === "all" ? appointments : appointments.filter((item) => item.status === filter);
  return <><PageTitle eyebrow="Lịch hẹn" title="Điều phối lịch khám" text="Duyệt yêu cầu, mở ca khám và theo dõi trạng thái trong thời gian thực." action={<div className="portal-filter"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>Tất cả</button><button className={filter === "pending" ? "active" : ""} onClick={() => setFilter("pending")}>Chờ duyệt</button><button className={filter === "confirmed" ? "active" : ""} onClick={() => setFilter("confirmed")}>Đã duyệt</button></div>} /><section className="partner-panel full"><div className="request-list">{filtered.map((appointment) => <AppointmentRow key={appointment.id} appointment={appointment} actions={appointment.status === "pending" && canSchedule ? <><button className="decline" onClick={() => onDecision(appointment, "cancelled")}>Từ chối</button><button className="accept" onClick={() => onDecision(appointment, "confirmed")}>✓ Duyệt lịch</button></> : appointment.status === "confirmed" && canMedical ? <button className="open-visit" onClick={() => onComplete(appointment)}>Mở ca khám</button> : <span className={`portal-status ${appointment.status}`}>{appointment.status === "completed" ? "Đã hoàn tất" : appointment.status === "cancelled" ? "Đã hủy" : appointment.status === "pending" ? "Chờ người có quyền duyệt" : "Đã xác nhận"}</span>} />)}</div></section></>;
}

function RecordsPanel({ data, appointments, onComplete }: { data: AppData; appointments: Appointment[]; onComplete: (appointment: Appointment) => void }) {
  const uniquePets = [...new Map(appointments.map((item) => [item.pet_id, item])).values()];
  return <><PageTitle eyebrow="Hồ sơ pet" title="Hồ sơ đã được cấp quyền" text="Chỉ xem hồ sơ của pet có lịch tại cơ sở. Quyền truy cập được kiểm tra ở backend." /><div className="record-grid">{uniquePets.map((item) => { const pet = data.partnerPets.find((value) => value.id === item.pet_id); return <article className="portal-pet-card" key={item.pet_id}><div><span>{item.pet_avatar ?? pet?.avatar ?? "🐾"}</span><i>✓</i></div><h2>{item.pet_name}</h2><p>{item.pet_breed}</p><dl><div><dt>Chủ nuôi</dt><dd>{item.owner_email}</dd></div><div><dt>Lần gần nhất</dt><dd>{dt(item.scheduled_at)}</dd></div><div><dt>Dị ứng</dt><dd>{pet?.allergies || "Không ghi nhận"}</dd></div></dl>{item.status === "confirmed" ? <button onClick={() => onComplete(item)}>Cập nhật sau khám →</button> : <span className="record-readonly">Chỉ cập nhật sau khi lịch được xác nhận</span>}</article>; })}</div></>;
}

function ProductsPanel({ products, onAdd, onSave }: { products: Product[]; onAdd: () => void; onSave: (product: Product, stock: number, active: boolean) => void }) {
  const [drafts, setDrafts] = useState<Record<string, number>>({});
  return <><PageTitle eyebrow="Cửa hàng" title="Quản lý sản phẩm" text="Tồn kho và trạng thái bán được đồng bộ ngay với trang mua sắm." action={<button className="portal-primary" onClick={onAdd}>+ Đăng sản phẩm</button>} /><section className="product-table"><div className="product-table-head"><span>Sản phẩm</span><span>Giá</span><span>Đã bán</span><span>Tồn kho</span><span>Hiển thị</span><span/></div>{products.map((product) => <div className="product-table-row" key={product.id}><div><span className={`tone-${product.visual_tone}`}>{product.visual}</span><p><b>{product.name}</b><small>{product.category}</small></p></div><b>{money(product.price)}</b><span>{product.sold}</span><input type="number" min="0" value={drafts[product.id] ?? product.stock} onChange={(event) => setDrafts((current) => ({ ...current, [product.id]: Math.max(0, Number(event.target.value)) }))}/><span className={product.active ? "product-live" : "product-hidden"}>{product.active ? "Đang bán" : "Đã ẩn"}</span><button onClick={() => onSave(product, drafts[product.id] ?? product.stock, Boolean(product.active))}>Lưu</button></div>)}{!products.length && <div className="partner-empty roomy"><span>◇</span><b>Chưa có sản phẩm</b><p>Đăng sản phẩm đầu tiên cho cơ sở này.</p><button className="portal-primary" onClick={onAdd}>+ Đăng sản phẩm</button></div>}</section></>;
}

function OrdersPanel({ orders, onStatus }: { orders: Order[]; onStatus: (order: Order, status: "paid" | "cancelled" | "fulfilled") => void }) {
  const labels: Record<Order["status"], string> = { pending_payment: "Chờ thanh toán", payment_review: "Chờ đối soát", paid: "Đã thanh toán", cancelled: "Đã hủy", fulfilled: "Đã hoàn tất" };
  return <><PageTitle eyebrow="Bán hàng" title="Đơn hàng từ khách" text="Đơn được tạo từ app khách hàng và đồng bộ trực tiếp vào database của cửa hàng." /><section className="partner-orders">{orders.map((order) => <article key={order.id}><header><div><small>Mã đơn</small><b>{order.order_code}</b></div><span className={`order-status ${order.status}`}>{labels[order.status]}</span></header><p><b>{order.owner_email}</b><small>{dt(order.created_at)}</small></p><div>{order.items?.map((item) => <span key={item.id}><b>{item.product_name}</b><em>{item.quantity} × {money(item.unit_price)}</em></span>)}</div><footer><strong>{money(order.total_amount)}</strong><div>{order.status === "pending_payment" && <button className="decline" onClick={() => onStatus(order, "cancelled")}>Hủy đơn</button>}{order.status === "payment_review" && <><button className="decline" onClick={() => onStatus(order, "cancelled")}>Từ chối</button><button className="accept" onClick={() => onStatus(order, "paid")}>Xác nhận đã nhận tiền</button></>}{order.status === "paid" && <button className="accept" onClick={() => onStatus(order, "fulfilled")}>Hoàn tất đơn</button>}</div></footer></article>)}{!orders.length && <div className="partner-empty roomy"><span>◫</span><b>Chưa có đơn hàng</b><p>Khi khách checkout, đơn sẽ xuất hiện tại đây.</p></div>}</section></>;
}

function SettingsPanel({ partner, onStatus, onProfile }: { partner: Partner; onStatus: (open: boolean, accepting: boolean) => void; onProfile: (payload: Record<string, unknown>) => void }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); onProfile({ name: f.get("name"), address: f.get("address"), phone: f.get("phone"), hours: f.get("hours"), services: f.get("services"), latitude: Number(f.get("latitude")), longitude: Number(f.get("longitude")) }); }; return <><PageTitle eyebrow="Cài đặt" title="Vận hành cơ sở" text="Các thay đổi ở đây được phản ánh trực tiếp lên bản đồ và ứng dụng khách hàng." /><div className="settings-grid"><section className="partner-panel"><h2>Trạng thái trực tiếp</h2><div className="setting-row"><div><b>Mở cửa trên bản đồ</b><p>Cho khách biết cơ sở đang hoạt động.</p></div><label className="switch"><input type="checkbox" checked={Boolean(partner.open_now)} onChange={(event) => void onStatus(event.target.checked, Boolean(partner.accepting_appointments))}/><span/></label></div><div className="setting-row"><div><b>Nhận lịch khám mới</b><p>Cho phép người dùng gửi yêu cầu đặt lịch.</p></div><label className="switch"><input type="checkbox" checked={Boolean(partner.accepting_appointments)} onChange={(event) => void onStatus(Boolean(partner.open_now), event.target.checked)}/><span/></label></div><div className={`verification-card ${partner.verified ? "verified" : "pending"}`}><b>{partner.verified ? "✓ Cơ sở đã xác minh" : "⌛ Đang chờ PetCare xác minh"}</b><p>{partner.verified ? "Được hiển thị công khai trên bản đồ và cửa hàng." : "Sản phẩm và vị trí chưa hiển thị cho khách cho đến khi được duyệt."}</p></div></section><section className="partner-panel"><h2>Hồ sơ cơ sở</h2><form className="partner-profile-form" onSubmit={submit}><label>Tên cơ sở<input name="name" required maxLength={160} defaultValue={partner.name} /></label><label>Địa chỉ<input name="address" required maxLength={300} defaultValue={partner.address} /></label><label>Điện thoại<input name="phone" required maxLength={30} defaultValue={partner.phone} /></label><label>Giờ hoạt động<input name="hours" required maxLength={160} defaultValue={partner.hours} /></label><label>Dịch vụ<textarea name="services" required maxLength={500} defaultValue={partner.services.replace(/\|/g, ", ")} /></label><div><label>Vĩ độ<input name="latitude" type="number" step="any" min="-90" max="90" required defaultValue={partner.latitude} /></label><label>Kinh độ<input name="longitude" type="number" step="any" min="-180" max="180" required defaultValue={partner.longitude} /></label></div><button className="portal-primary">Lưu hồ sơ cơ sở</button></form></section></div></>;
}

function PortalModal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="portal-modal-bg" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><div className="portal-modal" role="dialog" aria-modal="true" aria-label={title}><header><div><span>PetCare Partner</span><h2>{title}</h2></div><button onClick={onClose}>×</button></header>{children}</div></div>; }

function MedicalModal({ appointment, busy, onClose, onSubmit }: { appointment: Appointment; busy: boolean; onClose: () => void; onSubmit: (payload: Record<string, unknown>) => void }) {
  const [isVaccine, setIsVaccine] = useState(appointment.reason.toLowerCase().includes("tiêm"));
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); onSubmit({ diagnosis: f.get("diagnosis"), treatment: f.get("treatment"), prescription: f.get("prescription"), clinician: f.get("clinician"), note: f.get("note"), vaccineName: isVaccine ? f.get("vaccineName") : "", batchNumber: isVaccine ? f.get("batchNumber") : "", nextDueAt: isVaccine ? f.get("nextDueAt") : "" }); };
  return <PortalModal title={`Cập nhật hồ sơ · ${appointment.pet_name}`} onClose={onClose}><div className="modal-pet-summary"><span>{appointment.pet_avatar ?? "🐾"}</span><div><b>{appointment.pet_name}</b><small>{appointment.pet_breed} · {appointment.reason}</small></div><i>🔒 Có quyền từ lịch hẹn</i></div><form className="medical-form" onSubmit={submit}><label>Chẩn đoán<input name="diagnosis" required maxLength={500} placeholder="Kết luận sau thăm khám" /></label><label>Hướng điều trị<textarea name="treatment" required maxLength={800} placeholder="Thủ thuật, chăm sóc, theo dõi..." /></label><label>Đơn thuốc<textarea name="prescription" maxLength={800} placeholder="Tên thuốc, liều lượng, số ngày" /></label><label>Bác sĩ phụ trách<input name="clinician" required maxLength={120} placeholder="BS. Nguyễn Gia Hân" /></label><label>Ghi chú cho chủ pet<textarea name="note" maxLength={800} placeholder="Dấu hiệu cần theo dõi tại nhà" /></label><label className="vaccine-check"><input type="checkbox" checked={isVaccine} onChange={(event) => setIsVaccine(event.target.checked)}/> Ca khám có tiêm/chích ngừa</label>{isVaccine && <div className="vaccine-fields"><label>Tên vaccine<input name="vaccineName" required placeholder="Vaccine 7 bệnh" /></label><label>Số lô<input name="batchNumber" required placeholder="VN7-260718-B2" /></label><label>Ngày nhắc tiếp theo<input name="nextDueAt" type="date" /></label></div>}<footer><button type="button" onClick={onClose}>Hủy</button><button className="portal-primary" disabled={busy}>{busy ? "Đang đồng bộ..." : "Hoàn tất & cập nhật hồ sơ"}</button></footer></form></PortalModal>;
}

function ProductModal({ partnerId, busy, onClose, onSubmit }: { partnerId: string; busy: boolean; onClose: () => void; onSubmit: (payload: Record<string, unknown>) => void }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); onSubmit({ partnerId, name: f.get("name"), category: f.get("category"), price: Number(f.get("price")), stock: Number(f.get("stock")), visual: f.get("visual"), description: f.get("description") }); }; return <PortalModal title="Đăng sản phẩm mới" onClose={onClose}><form className="medical-form" onSubmit={submit}><div className="product-form-grid"><label>Tên sản phẩm<input name="name" required maxLength={160} /></label><label>Danh mục<select name="category"><option>Thức ăn</option><option>Phụ kiện</option><option>Đồ chơi</option><option>Chăm sóc</option><option>Thuốc thú y</option></select></label><label>Giá bán (VND)<input name="price" type="number" min="0" required /></label><label>Tồn kho<input name="stock" type="number" min="0" required /></label><label>Biểu tượng sản phẩm<input name="visual" maxLength={8} defaultValue="🎁" /></label></div><label>Mô tả<textarea name="description" required maxLength={500} /></label><footer><button type="button" onClick={onClose}>Hủy</button><button className="portal-primary" disabled={busy}>{busy ? "Đang đăng..." : "Đăng lên cửa hàng"}</button></footer></form></PortalModal>; }
